//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomowyFastFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        public int ID_Pracownika { get; set; }
        public string Nick { get; set; }
        public string Password { get; set; }
        public int Autoryzacja { get; set; }
    }
}
